// Owned regions in files the harness shares with people: marked blocks inside a
// file, or whole generated files. Each carries a hash of what was written, so a
// hand edit is detected and never silently overwritten.
import { createHash } from "node:crypto";

export const hash = (s: string) => createHash("sha256").update(s.replaceAll("\r\n", "\n").trim()).digest("hex").slice(0, 12);

export type Upsert = { text: string; state: "created" | "updated" | "unchanged" | "hand-edited" };

const begin = (name: string) => new RegExp(`<!-- uh:begin ${name}(?: sha=([0-9a-f]+))? -->\\r?\\n`);
const end = (name: string) => new RegExp(`\\r?\\n<!-- uh:end ${name} -->`);

/** Put `content` in block `name` of `file` (undefined = no file yet). */
export function upsertBlock(file: string | undefined, name: string, content: string, opts: { force?: boolean; prefix?: string } = {}): Upsert {
  const block = `<!-- uh:begin ${name} sha=${hash(content)} -->\n${content.trim()}\n<!-- uh:end ${name} -->`;
  if (file === undefined) return { text: `${opts.prefix ? `${opts.prefix}\n\n` : ""}${block}\n`, state: "created" };

  const crlf = file.includes("\r\n");
  const out = (s: string) => (crlf ? s.replaceAll(/\r?\n/g, "\r\n") : s);
  const b = begin(name).exec(file);
  if (!b) return { text: out(`${file.trimEnd()}\n\n${block}\n`), state: "updated" };
  const e = end(name).exec(file.slice(b.index));
  if (!e) throw new Error(`block '${name}' has a begin marker but no end marker`);

  const bodyStart = b.index + b[0].length;
  const bodyEnd = b.index + e.index;
  const current = file.slice(bodyStart, bodyEnd);
  if (b[1] && hash(current) !== b[1] && !opts.force) return { text: file, state: "hand-edited" };
  if (hash(current) === hash(content)) return { text: file, state: "unchanged" };
  const next = file.slice(0, b.index) + block + file.slice(bodyEnd + e[0].length);
  return { text: out(next), state: "updated" };
}

/** A file owned entirely by the harness, with its hash in the first line. */
export function generatedFile(file: string | undefined, content: string, source: string, opts: { force?: boolean } = {}): Upsert {
  const header = (h: string) => `<!-- generated by universal-harness from ${source}; do not edit. sha=${h} -->`;
  const text = `${header(hash(content))}\n\n${content.trim()}\n`;
  if (file === undefined) return { text, state: "created" };
  const m = /^<!-- generated by universal-harness .* sha=([0-9a-f]+) -->\r?\n\r?\n?/.exec(file);
  if (!m) return opts.force ? { text, state: "updated" } : { text: file, state: "hand-edited" };
  const body = file.slice(m[0].length);
  if (hash(body) !== m[1] && !opts.force) return { text: file, state: "hand-edited" };
  return hash(body) === hash(content) ? { text: file, state: "unchanged" } : { text, state: "updated" };
}
