// The instruction blocks provisioning writes into a project's repo. The full
// brief goes to its own file; these blocks stay short because they share an
// entry file (AGENTS.md) with the project's own conventions and size limits.
import type { Agent, AgentRegistry, Project } from "../schema.ts";
import { reachGap } from "../validate.ts";

export const BRIEF_PATH = ".uh/brief.md";

/** Shared by every agent: the part of AGENTS.md that makes a takeover cheap. */
export function essentials(p: Project, reg: AgentRegistry): string {
  const name = (id: string) => reg.agents.find((a) => a.id === id)?.name ?? id;
  const L: string[] = [];
  L.push("## Workspace and handoff (generated)", "");
  L.push(`Generated by universal-harness from the \`${p.project.id}\` workspace manifest. Edit the manifest and re-run \`uh provision\`; edits to this block are refused.`, "");

  L.push("**Taking over work another agent started?** Find out where it stands before changing anything:", "");
  L.push("- If `uh` is installed: `uh pickup [ref]` (ref: an issue key, PR number, branch or task slug; none = the current branch).");
  const records = p.continuity.records;
  if (records.length) {
    L.push(`- Otherwise read: ${records.map((r) => r.location).join("; ")}.`);
  }
  L.push("");

  if (records.length) {
    L.push("**Keep the handoff current as you work.** You can be cut off at any moment (usage limit, crash), and so could the agent before you:", "");
    for (const r of records) L.push(`- ${r.location}: ${r.cadence}.${r.reachable_by.includes("cloud") ? "" : " Local only: cloud agents cannot see it, so also leave the essentials where they can (pushed branch, PR)."}`);
    L.push("");
  }

  const id = p.identity;
  if (id.mention || id.branch) {
    L.push("**Name things so the next agent can find them:**", "");
    const example = id.examples.map((e) => /\[[^\]]+\]/.exec(e)?.[0]).find(Boolean);
    if (id.mention) L.push(`- Cite the item in PR titles and commit subjects as \`${id.mention}\`${example ? `, e.g. \`${example}\`` : ""}.`);
    if (id.branch) L.push(`- Branch: \`${id.branch}\`.`);
    L.push("");
  }

  const loc = (id: string) => p.carriers.find((c) => c.id === id)?.locator ?? id;
  const byHand = p.flows
    .map((f) => ({ f, mirrors: f.carriers.mirrors.filter((m) => m.sync === "manual").map((m) => loc(m.carrier)) }))
    .filter((x) => x.mirrors.length);
  if (byHand.length) {
    L.push("**State kept by hand:** a state change is not done until every place below shows it.", "");
    for (const { f, mirrors } of byHand) L.push(`- ${f.id} (${f.items.join(", ")}): ${loc(f.carriers.primary)}, then ${mirrors.join(", ")}`);
    L.push("");
  }

  const humanOnly = p.resources.filter((r) => r.access.every((a) => a.actor === "human")).map((r) => `${r.id} (${r.provider})`);
  const humanRoles = p.roles.filter((r) => r.actor === "human").map((r) => r.id);
  if (humanOnly.length || humanRoles.length) {
    L.push(`**Stop and ask the ${humanRoles[0] ?? "maintainer"}** for anything that needs ${humanOnly.join(", ") || "a human role"}; do not work around it.`, "");
  }

  const agentRoles = p.roles.filter((r) => r.actor === "agent");
  if (agentRoles.length) {
    L.push("**Roles** (first choice → fallbacks):", "");
    for (const r of agentRoles) L.push(`- ${r.id}: ${r.agents.map(name).join(" → ")}`);
    L.push("");
  }

  L.push(`Full brief (resources, flows, gates, procedures): [\`${BRIEF_PATH}\`](${BRIEF_PATH}).`);
  return L.join("\n");
}

/** One agent's projection, for an entry file only that agent reads (CLAUDE.md). */
export function agentBlock(p: Project, reg: AgentRegistry, agent: Agent, provisionedMcp: string[] = []): string {
  const L: string[] = [];
  L.push(`## For ${agent.name} (generated)`, "");
  const mine = p.roles.filter((r) => r.agents.includes(agent.id));
  if (mine.length) {
    L.push("Your roles here:", "");
    for (const r of mine) {
      const rank = r.agents.indexOf(agent.id);
      L.push(`- **${r.id}** (${rank === 0 ? "first choice" : `fallback #${rank}`}): ${r.summary}${r.writes.length ? `. Write only: ${r.writes.map((w) => `\`${w}\``).join(", ")}` : ""}`);
    }
    L.push("");
  } else {
    L.push("No role is bound to you here; you may still be asked to take one over.", "");
  }

  const gaps = new Map<string, string>();
  for (const r of mine) {
    for (const u of r.uses) {
      const res = p.resources.find((x) => x.id === u);
      const gap = res && reachGap(agent, res, provisionedMcp);
      if (res && gap) gaps.set(res.id, gap);
    }
  }
  if (gaps.size) {
    L.push("You cannot reach these yet; ask the maintainer instead of guessing:", "");
    for (const [id, gap] of gaps) L.push(`- ${id}: needs ${gap}`);
    L.push("");
  }

  const entries = p.procedures.filter((x) => x.entry[agent.id]);
  if (entries.length) {
    L.push("Your entry points for project procedures:", "");
    for (const x of entries) L.push(`- ${x.id}: \`${x.entry[agent.id]}\``);
    L.push("");
  }
  if (agent.branch_prefixes[0]) L.push(`Your branches start with \`${agent.branch_prefixes[0]}/\`.`, "");
  for (const n of agent.notes) L.push(`- ${n}`);
  return L.join("\n").trimEnd();
}
