// Renders a project manifest into the agent-facing brief: the part of AGENTS.md
// that tells any agent how this workspace works. With `agent`, the brief is
// projected for that agent: its roles, its entry points, its reach gaps.
import type { AgentRegistry, Flow, Project } from "./schema.ts";
import { reachGap } from "./validate.ts";

export function brief(p: Project, reg: AgentRegistry, agentId?: string): string {
  const agent = agentId ? reg.agents.find((a) => a.id === agentId) : undefined;
  if (agentId && !agent) throw new Error(`unknown agent '${agentId}'`);
  const L: string[] = [];

  L.push(`# Workspace brief: ${p.project.id}${agent ? ` (for ${agent.name})` : ""}`, "");
  L.push(`> Generated by universal-harness from \`project.yaml\`. Edit the manifest, not this file.`, "");
  L.push(p.project.summary, "");

  if (agent) {
    const mine = p.roles.filter((r) => r.agents.includes(agent.id));
    L.push("## Your roles here", "");
    if (!mine.length) L.push("None bound. You may still be asked to take over a role; see Roles.", "");
    for (const r of mine) {
      const rank = r.agents.indexOf(agent.id);
      L.push(`- **${r.id}**: ${r.summary} (${rank === 0 ? "first choice" : `fallback #${rank}`})`);
    }
    if (mine.length) L.push("");
  }

  L.push("## Where things live", "");
  L.push("| Resource | Kind | Locator | How to reach it |", "|---|---|---|---|");
  for (const r of p.resources) {
    const how = r.access
      .map((x) => (x.actor === "human" ? `**human only** (${x.via})` : `${x.via}${x.tool ? `: ${x.tool}` : ""}`))
      .join("; ");
    const gap = agent ? reachGap(agent, r) : undefined;
    L.push(`| ${r.id} | ${r.kind} (${r.provider}) | ${r.locator} | ${how}${gap ? ` ⚠ you lack ${gap}` : ""} |`);
  }
  L.push("", "Human-only resources are handover points: stop and ask the maintainer, do not work around them.", "");

  L.push("## What to read, and what wins", "");
  const order = ["normative", "descriptive", "ephemeral"] as const;
  for (const level of order) {
    const ks = p.knowledge.filter((k) => k.authority === level);
    if (!ks.length) continue;
    L.push(`**${level}**`, "");
    for (const k of ks) {
      const truth = k.truth_for.length ? ` source of truth for: ${k.truth_for.join(", ")}.` : "";
      L.push(`- \`${k.ref}\`: ${k.role}${k.lifetime !== "permanent" ? ` (${k.lifetime})` : ""}.${truth}`);
    }
    L.push("");
  }

  L.push("## Work flows", "");
  for (const f of p.flows) L.push(...renderFlow(f, p), "");

  L.push("## Roles", "");
  for (const r of p.roles) {
    const who = r.actor === "agent" ? r.agents.join(" → ") || "unbound" : r.actor;
    L.push(`- **${r.id}** (${who}): ${r.summary}`);
    if (r.inbox.length) L.push(`  - inbox: ${r.inbox.join(", ")}`);
    if (r.writes.length) L.push(`  - writes only: ${r.writes.map((w) => `\`${w}\``).join(", ")}`);
    if (r.requires.length) L.push(`  - requires: ${r.requires.join(", ")}`);
  }
  L.push("");

  L.push("## Procedures and rules", "");
  for (const pr of p.procedures) {
    const enforced = pr.enforced_by
      ? `enforced by ${[pr.enforced_by.ci && `CI \`${pr.enforced_by.ci}\``, pr.enforced_by.hook && `hook \`${pr.enforced_by.hook}\``].filter(Boolean).join(", ")}`
      : pr.kind === "recipe" ? "" : "**not enforced: nothing fails if you skip it**";
    const when = pr.when?.paths.length ? ` When you touch ${pr.when.paths.map((x) => `\`${x}\``).join(", ")}.` : pr.when?.event ? ` When: ${pr.when.event}.` : "";
    const entry = agent && pr.entry[agent.id] ? ` Run it with \`${pr.entry[agent.id]}\`.` : "";
    L.push(`- **${pr.id}** (${pr.kind}): ${pr.summary}.${when}${entry}${enforced ? ` _${enforced}._` : ""}`);
    for (const cmd of pr.run) L.push(`  - \`${cmd}\``);
  }
  L.push("");

  L.push("## Continuity: so the next agent can pick up", "");
  const c = p.continuity;
  const id = p.identity;
  if (id.mention) L.push(`- Cite items as \`${id.mention}\` in PR titles and commit subjects.`);
  for (const k of id.keys) L.push(`- Key \`${k.id}\`: \`${k.pattern}\`${k.note ? `. ${k.note}` : ""}.`);
  if (id.branch) L.push(`- Branch name: \`${id.branch}\`${agent?.branch_prefixes[0] ? `, yours start with \`${agent.branch_prefixes[0]}/\`` : ""}.`);
  for (const e of id.examples) L.push(`- e.g. ${e}`);
  for (const r of c.records) {
    L.push(`- ${cap(r.level)} record: ${r.location}. Update it ${r.cadence}. Readable by ${r.reachable_by.join(" and ")} agents.`);
  }
  L.push(
    "",
    "You can be stopped at any moment (usage limit, crash). Keep the records above current as you go;",
    "a record written only at the end is never written when it matters.",
    "",
  );

  if (agent?.notes.length) {
    L.push(`## Notes for ${agent.name}`, "", ...agent.notes.map((n) => `- ${n}`), "");
  }
  return L.join("\n");
}

function renderFlow(f: Flow, p: Project): string[] {
  const L = [`### ${f.id}: ${f.summary}`, ""];
  L.push(`Items: ${f.items.join(", ")}.${f.defined_in ? ` Defined in \`${f.defined_in}\`.` : ""}`);
  const carrier = (id: string) => p.carriers.find((c) => c.id === id);
  const prim = carrier(f.carriers.primary);
  L.push(`State lives in **${prim?.locator ?? f.carriers.primary}** (truth)${f.carriers.mirrors.length ? `, mirrored in ${f.carriers.mirrors.map((m) => `${carrier(m.carrier)?.locator ?? m.carrier} (${m.sync})`).join(", ")}` : ""}.`);
  if (f.carriers.mirrors.some((m) => m.sync === "manual")) {
    L.push("Manual mirrors are your job: a transition is not done until every mirror shows it.");
  }
  L.push("", "| From | To | Who | Gate | Effects |", "|---|---|---|---|---|");
  for (const t of f.transitions) {
    const from = Array.isArray(t.from) ? t.from.join(", ") : t.from;
    L.push(`| ${from} | ${t.to} | ${t.by} | ${t.checks.join(", ") || "—"} | ${t.effects.join("; ") || "—"} |`);
  }
  return L;
}

const cap = (s: string) => s[0]!.toUpperCase() + s.slice(1);
