import type { PickupReport } from "./pickup.ts";
import type { AgentRegistry, Project } from "./schema.ts";

const RECORD_LINES = 80;

const cap = (s: string) => s[0]!.toUpperCase() + s.slice(1);

export function renderPickup(r: PickupReport, project: Project, reg: AgentRegistry): string {
  const name = (id: string) => reg.agents.find((a) => a.id === id)?.name ?? id;
  const L: string[] = [];
  const title = r.keys.pr ? `PR #${r.keys.pr}` : (r.keys.branch ?? r.ref);
  L.push(`# Pickup: ${title}`, "");
  L.push(`Project **${r.project}**${r.agent ? `, for ${name(r.agent)}` : ""}. Asked for \`${r.ref || "(current branch)"}\`.`);
  L.push("", "> Generated by `uh pickup`: read-only, assembled from every place this item's state is kept.", "");

  L.push("## Identity", "");
  const keys = Object.entries(r.keys).filter(([k]) => k !== "agent");
  L.push(...keys.map(([k, v]) => `- ${k}: \`${v}\``));
  if (r.lastAgent) L.push(`- last worked on by: **${name(r.lastAgent)}** (branch prefix)`);
  if (r.agent && r.lastAgent && r.agent !== r.lastAgent) L.push("", `You are taking over from ${name(r.lastAgent)}.`);
  for (const n of r.notes) L.push("", n);
  L.push("");

  if (r.candidates.length > 1) {
    L.push("## Related items", "", "The ref matches several items. Pickup focused on the one marked ▶; name another to switch.", "");
    for (const c of r.candidates) L.push(`- ${c.keys.pr === r.keys.pr ? "▶ " : ""}${c.label}`);
    L.push("");
  }

  L.push("## Where it stands", "");
  if (!r.flows.length) L.push("Not found in any flow's carriers. See Gaps.", "");
  for (const f of r.flows) {
    const state = f.states.length ? f.states.join(" or ") : "unknown";
    L.push(`### ${f.flow}: **${state}**${f.basis === "mirrors" ? " (inferred from mirrors; the primary carrier did not say)" : ""}`, "");
    L.push("| Carrier | Reads | → state |", "|---|---|---|");
    for (const c of f.readings) {
      const rd = c.reading;
      const reads =
        rd.status === "found" ? `\`${rd.value}\`${rd.url ? ` ([link](${rd.url}))` : ""}${rd.detail ? ` ${rd.detail}` : ""}`
        : rd.status === "absent" ? `not found${rd.detail ? ` (${rd.detail})` : ""}`
        : rd.status === "unreadable" ? `**unreadable**: ${rd.reason}`
        : "no reader";
      L.push(`| ${c.carrier.id} (${c.role}) | ${reads} | ${c.states === null ? "—" : c.states.join(", ") || "no match"} |`);
    }
    for (const d of f.disagreements) L.push("", `⚠ ${d}`);
    L.push("");
    if (f.next.length) {
      L.push("Next:", "");
      for (const t of f.next) {
        const who = t.actor === "agent" ? `${t.by} (${t.agents.map(name).join(" → ")})` : `${t.by} (${t.actor})`;
        const you = r.agent && t.agents.includes(r.agent) ? " ← you can do this" : t.actor === "human" ? " ← hand to the maintainer" : "";
        L.push(`- ${t.from} → **${t.to}** by ${who}${you}`);
        for (const c of t.checks) {
          const p = project.procedures.find((x) => x.id === c);
          L.push(`  - gate: ${c}${p ? `: ${p.summary}${p.enforced_by?.ci ? ` (CI: ${p.enforced_by.ci})` : p.kind === "recipe" ? "" : " (not enforced)"}` : ""}`);
        }
        if (t.effects.length) L.push(`  - then: ${t.effects.join("; ")}`);
      }
      L.push("");
    }
  }

  for (const s of r.sections) L.push(`## ${s.title}`, "", s.body, "");

  if (r.changed) {
    L.push("## Changes on the branch", "");
    L.push(`${r.changed.length} file(s): ${r.changed.slice(0, 12).map((f) => `\`${f}\``).join(", ")}${r.changed.length > 12 ? ", …" : ""}`, "");
    for (const o of r.obligations) {
      const why = `triggered by ${o.triggeredBy.slice(0, 3).map((f) => `\`${f}\``).join(", ")}${o.triggeredBy.length > 3 ? ", …" : ""}`;
      L.push(o.missing.length
        ? `- ⚠ **${o.id}**: ${o.summary}. ${cap(why)}, but the branch does not change ${o.missing.map((m) => `\`${m}\``).join(", ")}.`
        : `- ${o.id}: ${o.summary} (${why}); its files are changed too.`);
    }
    if (r.obligations.length) L.push("");
  }

  L.push("## Continuity records", "");
  for (const rec of r.records) {
    L.push(`### ${rec.level}: ${rec.location}`, "");
    if (!rec.found.length) {
      L.push(rec.location.startsWith("PR ") ? "See the PR sections above." : "Not found for this item.", "");
      continue;
    }
    for (const f of rec.found) {
      const lines = f.text.trimEnd().split("\n");
      L.push(`From \`${f.from}\`${lines.length > RECORD_LINES ? ` (first ${RECORD_LINES} of ${lines.length} lines)` : ""}:`, "");
      L.push("````markdown", ...lines.slice(0, RECORD_LINES), "````", "");
    }
  }

  if (r.gaps.length) L.push("## Gaps", "", "Not read, so not in this picture:", "", ...r.gaps.map((g) => `- ${g}`), "");
  L.push("## Before you start", "");
  L.push("- Read the project's normative knowledge (`uh brief`), then the records above.");
  L.push("- Update the session record as you go: you may be stopped at any moment, as the previous agent may have been.");
  return L.join("\n");
}
